name: flutter_wordle
description: "A new Flutter project."
publish_to: 'none'
version: 0.0.8

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  dynamic_color: ^1.6.6
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.3.7
  google_mobile_ads: ^3.0.0
  share_plus: ^7.1.0
  shared_preferences: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
